### ISSUE TITLE
Migrate wordpress to jekyll here

### ISSUE THREAD

**Issue by rufuspollock** [okfn/opendatacommons#4]
Why?

* Track licenses in a diff-able, PR-able form
* Easier for people to contribute
* Simpler, fewer moving parts
* It's a simple static website, and we don't need wordpress
* Use a consistent simple theme
* We use wordpress less and less
* No spam

## Tasks

* [x] Research how many pages / posts in opendatacommons
  * [x] Comments: 110. **Can lost these**. We can probably leave for now as mostly pingbacks. Most interesting are FAQs which should move to forum ...
  * [x] Media Files: 3 (dbc10.txt, odbl10.txt, odc_by_1.0_public_text.txt). **COPIED to `texts/`. Need to do redirects maybe (see notes section below)
  * [x] Posts: 32. None that important but nice to keep for historical purposes.
  * [x] Pages: 37. Some trimming to be done here ...
* [x] Backup / export content: https://github.com/oki-archive/opendatacommons.org-wordpress
* [ ] Skeleton the new site https://github.com/okfn/handbook-theme
  * [ ] copy over
  * [ ] tidy up taking out what we don't need
  * [ ] sort the front page
* [ ] Import content from backup https://github.com/oki-archive/opendatacommons.org-wordpress
  * [ ] pages
  * [ ] posts
  * [ ] tidy
    * [ ] remove unnecessary metadata and markdownify content
    * [ ] correct directory structure for pages
* [ ] Deploy on github pages
* [ ] Switch DNS (cloudflare)
  * [ ] Move old site to old.opendatacommons.org for now so we can still access if we need
  * [ ] Update DNS for site to github

## Converting from wordpress to jekyll

* Settled on https://github.com/rufuspollock/pywordpress as that could work via ruby gem. Downsides
  * All html rather than markdown ...
  * Lost directory structure for pages
  * Lots of random metadata
* Can't install plugins on wordpress site (so no ben balter plugin) or turn on xml-rpc so we can't use https://github.com/rufuspollock/pywordpress
* exitwp: a pain as needed python 2.7 and some config

## Notes & Questions

* Preserving links to the plain text of the license? Do we need to? In old versions:
  * ODbL plain text link went to: http://www.opendatacommons.org/wp-content/uploads/2009/06/odbl-10.txt
  * More recently to: https://opendatacommons.org/files/2018/02/odbl-10.txt
  * By link: https://opendatacommons.org/files/2018/02/odc_by_1.0_public_text.txt and http://www.opendatacommons.org/wp-content/uploads/2010/01/odc_by_1.0_public_text.txt
  * PDDL: has no plain text directly linked afaict

## Future

* Add a FAQ or Forum link to navbar

**Comment by rufuspollock** [comment]
Please ping here if you'd like to help out the in the migration.

**Comment by sabas** [comment]
"Deploy on github pages" if you activate in the repo it should build on http://okfnlabs.org/opendatacommons
when it's completed you could add the CNAME file

**Comment by pnorman** [comment]
Preserving links to the license text is essential.

**Comment by marctjones** [comment]
@rufuspollock Let me know if you would like some help.

**Comment by rufuspollock** [comment]
@marctjones help would be awesome! Would you like to get the main pages in place - in a perfect world we'd re markdownify from the html export.

**Comment by rufuspollock** [comment]
@pnorman 

> Preserving links to the license text is essential.

No links will be broken - i share your concern with keeping all links intact.

**Comment by marctjones** [comment]
@rufuspollock I can take that on as a task to convert the **content** of the main pages to markdown. Just so we are on the same page, by main pages am I correct in assuming you mean https://opendatacommons.org/, https://opendatacommons.org/faq/licenses/, etc. ... .

**Comment by rufuspollock** [comment]
@marctjones yes - i mean pages rather than posts. See item above "Import content from backup https://github.com/oki-archive/opendatacommons.org-wordpress" - focus on the pages part. 😄

**Comment by mlinksva** [comment]
> Please ping here if you'd like to help out the in the migration.

I'd be willing to help if a migration is still desired.

I'm not sure whether github pages would be appropriate for a site with tons of legacy URLs some of which might need unsupported redirects, but it's worth investigating, and even if pages doesn't work out, migration to a static site still makes tons of sense.

One way to find the URLs that might be worth supporting (sort by captures to avoid probably spurious ones): <http://web.archive.org/web/*/http://opendatacommons.org/*>

**Comment by rufuspollock** [comment]
@mlinksva that would be great - please dive in. We had made a decent start here in this repo 😄

**Comment by mlinksva** [comment]
@rufuspollock could you give me write access to this repo? I'll take care of outstanding PRs, and it'll be slightly less friction overall than working in my own fork.

**Comment by rufuspollock** [comment]
@mlinksva done!
